name: Docker
on:
  push:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/docker.yml'
jobs:
  build:
    strategy:
      matrix:
        folder:
          - 'api-bench-gitlab-runner'
          - 'api-bench'
          - 'api-bench-build'
          - 'api-bench-gitea-action'
          - 'api-bench-history-website'
          - 'api-bench-history-microservice'
    name: Build ${{ matrix.folder }}
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: git fetch --all
      - run: docker build --build-arg="BUILD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" --build-arg="BUILD_TIME=now" containers/${{ matrix.folder }}
