name: Docker
on:
  push:
    branches:
      - master
    paths:
      - '/containers/*/Dockerfile'
      - '.github/workflows/docker-test.yml'
  pull_request:
    branches:
      - master
    paths:
      - '/containers/*/Dockerfile'
      - '.github/workflows/docker-test.yml'
jobs:
  build-gitlab:
    name: Build Image
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: cd containers/gitlab-runner && docker build

