name: ESLINT
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: $CURRENT_NODE_VERSION
      - run: npm ci
      - run: cd website && npm ci
      - run: npm run-script lint
  eslint-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: $CURRENT_NODE_VERSION
      - run: npm ci
      - run: cd website && npm ci
      - run: cd website && npm run-script lint

