name: Docker
on:
  push:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/hadolint.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/hadolint.yml'
jobs:
  build-gitlab:
    name: HadoLint Gitlab
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench-gitlab-runner/Dockerfile
  build-gitea:
    name: HadoLint Gitea
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench-gitea-action/Dockerfile
  build-framework:
    name: HadoLint Framework
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench/Dockerfile
  build-microservice:
    name: HadoLint History Microservice
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench-history-microservice/Dockerfile
  build-website:
    name: HadoLint History Website
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench-history-website/Dockerfile
  build-build:
    name: HadoLint Build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /lusr/local/bin/hadolint
      - run: hadolint containers/api-bench-build/Dockerfile
