name: MARKDOWN-LINT
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ CURRENT_NODE_VERSION }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ CURRENT_NODE_VERSION }}
    - run: npm ci
    - run: npm run-script lint-md
