name: MARKDOWN-LINT
on:
  push:
    branches:
    - master
    paths:
    - '**.md'
    - '**.json'
    - '.github/workflows/**'
  pull_request:
    branches:
    - master
    paths:
    - '**.md'
    - '**.json'
    - '.github/workflows/**'
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts/*' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - run: npm ci
      - run: npm run-script lint-md
  framework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - run: cd framework && npm ci
      - run: cd framework && npm run-script lint-md
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - run: cd website && npm ci
      - run: cd website && npm run-script lint-md
