name: STYLELINT
on:
  push:
    branches:
    - master
    paths:
    - '**.css'
    - '**.json'
    - '.github/workflows/stylelint.yml'
  pull_request:
    branches:
    - master
    paths:
    - '**.css'
    - '**.json'
    - '.github/workflows/stylelint.yml'
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts/*' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - run: cd website && npm ci
      - run: cd website && npm run-script lint-styles
  duplicate-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - run: cd website && npm ci
      - run: cd website && npm run-script lint-css
