name: UNITTEST
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - ${{ env.PREVIOUS_NODE_VERSION }}
        - ${{ env.CURRENT_NODE_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run-script test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        flag-name: run ${{ join(matrix.*, ' - ') }}
  unittest-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ env.CURRENT_NODE_VERSION }}
    - run: cd website && npm ci
    - run: cd website && npm run-script test
    - run: mv ./website/coverage ./
    - run: sed -i 's/SF:src/SF:website\/src/' ./coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        flag-name: run website
  end:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs:
    - unittest
    - unittest-website
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
