name: UNITTEST
on:
  push:
    branches:
    - master
    paths:
    - '**.ts'
    - '**.tsx'
    - '**.js'
    - '**.cjs'
    - '**.json'
    - '.github/workflows/unittest.yml'
  pull_request:
    branches:
    - master
    paths:
    - '**.ts'
    - '**.tsx'
    - '**.js'
    - '**.cjs'
    - '**.json'
    - '.github/workflows/unittest.yml'
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts/*' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  framework-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run-script test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.PREVIOUS_NODE_VERSION }}
  framework-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run-script test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.CURRENT_NODE_VERSION }}
  framework-integration-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.PREVIOUS_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run-script integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.PREVIOUS_NODE_VERSION }}
  framework-integration-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run-script integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.CURRENT_NODE_VERSION }}
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd website && npm ci
      - run: cd website && npm run-script test
      - run: mv ./website/coverage ./
      - run: sed -i 's/SF:src/SF:website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run website
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            website/package-lock.json
            package-lock.json
      - run: cd website && npm ci
      - run: cd website && npm run-script e2e
      - run: mv ./website/coverage ./
      - run: sed -i 's/SF:src/SF:website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run e2e
  end:
    runs-on: ubuntu-latest
    needs:
    - framework-previous
    - framework-current
    - framework-integration-current
    - framework-integration-previous
    - website
    - e2e
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
